import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

import Navbar from './components/navbar/page';
import Footer from './components/footer/page';

export default function Layout({ children }) {
  return (
    <html lang='en'>
      <body className='flex flex-col min-h-screen'>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
