import './globals.css';
import {
  QueryClient,
  QueryClientProvider,
  useQuery,
} from '@tanstack/react-query';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

import Navbar from './components/navbar/page';
import Footer from './components/footer/page';

const queryClient = new QueryClient();

export default function Layout({ children }) {
  return (
    // <QueryClientProvider client={queryClient}>
    <html lang='en'>
      <body className='flex flex-col min-h-screen'>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
    // </QueryClientProvider>
  );
}
